# Generated by Django 4.2.7 on 2023-11-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
